### ISSUE TITLE
ABL every time you start printer?

### ISSUE THREAD

**Issue by AndyShap2020** [scmanjarrez/OctoPrint-SmartABL#9] opened 2023-01-19 05:36 UTC
### Is your feature request related to a problem? Please describe.

I have my gcode set to default. I am forcing an ABL after 10days. I am forcing an ABL after 5 prints. I am set to ignore failed prints.

All seems to work fine, but I turn my printer off if I am not immediately doing another print.  Is it normal that is does an ABL at the first print, EVERY time  I power on? If I power off and on 4 times in the same day, it will do an ABL at the start of each of those 4 prints. 

### Describe the solution you'd like

I'd like it to ignore power on/off and follow the rules set in the options.

**Comment by scmanjarrez** [comment] 2023-01-19 07:35
Do you mind enabling logs for SmartABL (DEBUG) and sharing octoprint_SmartABL.logs? Also, are you using marlin? Do you have eeprom enabled?

**Comment by AndyShap2020** [comment] 2023-01-20 06:08
[octoprint-logs.zip](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10463603/octoprint-logs.zip)
Yes, I am using Marlin. I am using MRiscoc's firmware. I am pretty sure eeprom is enabled. How do I know for sure?

Is the behavior I am describing normal?

**Comment by AndyShap2020** [comment] 2023-01-20 06:09
I am just looking at the log. It is empty. Hang tight, I will verify logging is enabled and post back.

**Comment by AndyShap2020** [comment] 2023-01-20 06:15
Sorry about that. I have enabled logging and will let it run for a day or two and get back to you.

**Comment by scmanjarrez** [comment] 2023-01-20 08:17
You can verify that eeprom is enabled by doing a G29 (note the values) and then M500 manually, then query the eeprom information sendi M503, that command should report the same mesh points returned by G29. Or reboot and send M503 and check the values of the mesh.

**Comment by AndyShap2020** [comment] 2023-01-31 19:45
Thank you for your patience (I've had some big print jobs running).  Here are the results of my eeprom commands as well as the SmartABL logs:
[eeprom results.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10550205/eeprom.results.txt)
[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10550206/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment] 2023-01-31 20:51
Do you mind sharing your start gcode?

**Comment by AndyShap2020** [comment] 2023-01-31 20:54
Wow! Thank you for the quick response!  G-Code attached
[Start G-Code.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10550926/Start.G-Code.txt)

**Comment by scmanjarrez** [comment] 2023-01-31 22:13
Can you share the output from M420 V1? The pluging isn't recognizing the output, it states that you have an invalid mesh.

Also, enable `custom` under Leveling command in SmartABL settings. Currently, the plugin is sending "M420 S1 Z2, M500", which is recovering the mesh from eeprom, not triggering ABL. I don't find any G29 in the logs. 

In the logs, it seems that you have enabled failed prints in the counter.

**Comment by AndyShap2020** [comment] 2023-02-03 19:37
Thank you again for your patience.  I'm running some 24 hour jobs, so I need to wait for the jobs to finish.

Attached are results from G29 command and M420 V1.
[G29.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10582132/G29.txt)
[M420 V1.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10582133/M420.V1.txt)

I was thinking CUSTOM meant "don't do the default action, do this instead". And I thought the default WAS G29.  I have enabled custom now.  Also, what I want is for failed prints to NOT be taken into account in my "every 5 prints do an ABL" request. Would I UNCHECK the failed prints option to achieve this?

**Comment by scmanjarrez** [comment] 2023-02-03 21:03
Yes, checked means take into account failed prints. The default action is "use my gcode instead (because someone was using g29 with a lot of arguments, however that doesn't take into account M420 which means "load mesh instead ")

**Comment by AndyShap2020** [comment] 2023-02-03 21:10
OK.  I have the M420 command in there because I DO NOT want to run an ABL every time I print.  So, the m420 says use the stored mesh level info (I'm talking out loud here, not trying to teach you something!).  Are you saying I should remove the M420 command from my start Gcode and let SmartABL handle it? And if so, where is it getting the mesh level info in between fresh ABL's triggered by SmartABL?

**Comment by scmanjarrez** [comment] 2023-02-03 21:24
Nono, it's just a bug in my code. I didn't even think about that case. But you can use custom gcode while I add that fix and some other functions pending. Without the custom gcode, the plugin monitors G29* and M420, if it detects any of these, it sents it back to the printer if ABL  conditions are met (which is incorrect in the case of M420, it should sent at least G29, sending M420 back does nothing), otherwise M420 is sent instead.  I'm not in home now. I'll check the logs later. But when  I checked them, (I think) the ABL wasn't from me, because the plugin was sending M420, not G29

**Comment by AndyShap2020** [comment] 2023-02-03 21:27
Sorry, a little confusing...  I think you are telling me to just leave it all as is for now?

P.S.  I'm happy to do some beta testing for you if you would like. You certainly have been more then helpful and responsive!

**Comment by scmanjarrez** [comment] 2023-02-03 21:40
That would be helpful, I've switched to Klipper few weeks ago and I need to go back and forth to test marlin. For now, uncheck failedPrints and check custom (with G29 in the box). The plugin will manage your bed leveling according to the conditions.

**Comment by AndyShap2020** [comment] 2023-02-09 00:57
FYI, I've followed directions per your most recent comment. It still does an ABL Every time I turn on the printer.

**Comment by scmanjarrez** [comment] 2023-02-09 08:01
I needs the logs. Disabling the plugin doesn't trigger ABL?

**Comment by scmanjarrez** [comment] 2023-02-14 17:42
Hi, sorry for the delay, I've been pretty busy.

I've added a [prerelease for 0.1.4](https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.1.4rc0), do you mind checking it? I've fixed the bug with M420 not triggering ABL when required.

**Comment by AndyShap2020** [comment] 2023-02-14 19:55
Should I leave CUSTOM,DAYS, # Prints and FAILED all checked in SmartABL?  Should I leave  M420 enabled in g-code?

Not sure how to install from a zip file into Octoprint., I'll figure that out.

**Comment by scmanjarrez** [comment] 2023-02-14 19:57
Configure it as you want, you don't need to check FAILED in settings. Leave M420 in gcode, yes, the plugin should use g29 instead.

**Comment by scmanjarrez** [comment] 2023-02-20 18:43
Did you manage to install it? Is it working now? 

If you still don't know how to install, go to settings, plugin manager, get more, and paste this link under the box "... from url" `https://github.com/scmanjarrez/OctoPrint-SmartABL/archive/refs/tags/0.1.4rc0.zip` and click install

**Comment by AndyShap2020** [comment] 2023-02-20 18:48
Hi Sergio,  Yes, I got it installed.  I am not sure how it is working (thus I haven't responded yet).  I have it set for 10 days or 5 prints.  I had a 21 hour print and maybe 1 or two others. It did an ABL on the next print. So, not 10 days (1 day) and not 5 prints (about 3 prints).  I really want to do a few more prints before I say anything.

P.S.  Does the failed prints option include stopped prints? I pretty much never have a failed print where the printer stops.  I have MANY prints that aren't going well, so I stop the print.  Hopefully, stopped prints are included in failed prints.

**Comment by scmanjarrez** [comment] 2023-02-20 18:50
Yes, cancelled and stopped prints count if enabled (checked). Only successful prints count if disabled (unchecked).
Ok, also, do you have the button under print information pressed on restricted? 
![image](https://user-images.githubusercontent.com/9284124/220181305-37337216-ea82-485f-9f78-574fdecab367.png)

I still don't understand why it's triggering the ABL, clearly the logs show ABL skip (no G29 sent to printer), so there is something else I'm missing, maybe is incompatible with another plugin? 🤔

**Comment by AndyShap2020** [comment] 2023-02-20 19:06
P.S. As noted on the screen print you just loaded, my Octoprint DOES NOT show a Green ABL restricted. It is a blank square box. It DOES show ABL Always.  I can't tell if ABL always is selected though. Does it change color or anything when selected? 

![image](https://user-images.githubusercontent.com/71109919/220182945-7edc30b5-6841-4412-90c2-40f16fbc8caa.png)

**Comment by scmanjarrez** [comment] 2023-02-20 19:08
lol, yes, it was supposed to be green, and blue when abl always is pressed.
Like this in v0.1.4
![image](https://user-images.githubusercontent.com/9284124/220183219-995eb651-a4b8-47c5-82dc-8e0d2f14b20e.png)
![image](https://user-images.githubusercontent.com/9284124/220183252-123d3853-dd6b-4884-8681-5853869c2e62.png)

Do you have any theme related plugin?

**Comment by AndyShap2020** [comment] 2023-02-20 20:17
I have "Themeify" plugin enabled.  I'd hate to lose it.  I have disabled it and the SmartABL portion looks correct.  I assume the middle portion tells me how many prints since last ABL?  Is there any way to incorporate SmartABL to be used alongside Themeify?

I'll keep an eye out to see if the issues I have been having are resolved by disabling Themeify.

**Comment by scmanjarrez** [comment] 2023-02-20 20:27
I have enabled themeify as well, and it works for me. Do you have custom css? What is your themeify configuration? I don't think themeify is the one triggering ABL. The middle part is the current_prints/prints_set_for_abl, when the first part is the same as the second, ABL is triggered (or by date, but that information isn't shown)

**Comment by AndyShap2020** [comment] 2023-02-20 20:50
![Themeify screen 1](https://user-images.githubusercontent.com/71109919/220196313-d9166972-bf74-41ee-b2d5-f6cf6490d6dc.jpg)
![Themeify screen 2](https://user-images.githubusercontent.com/71109919/220196320-2d3de3ab-bc7a-44ee-bf32-3ee599b4084a.jpg)

**Comment by scmanjarrez** [comment] 2023-02-28 16:07
Sorry. I found the problem, it seems like the culprit is the Material Light UI theme. Using the others kinda work. I think you can "disable" the theme but still being able to use custom css (that's what I do, because Material UI lose lot of button colors).

**Comment by AndyShap2020** [comment] 2023-02-28 18:06
I'll take a look.  I was doing testing of the new release, I got to 4/5 prints and then, 20 hours into a 22 hour print, our power shut off.   Octoprint reset the print count back to 0. :-( 

I'll keep testing.

**Comment by scmanjarrez** [comment] 2023-02-28 18:15
Yes, that's an intended behavior, when you start a print, the counter is set to 0, then on completion it's increased.

**Comment by AndyShap2020** [comment] 2023-03-04 22:43
I don't know if we are there yet. I started a print and it did an ABL. The print failed, and I started a new print. It did an ABL again. That second print failed and I started a third ABL again. I don't think it should have been doing an ABL each time (The count DID remain at 0/5, as it should since I never got a successful print.

Also, Can I get a screen print of your CSS entries, I'd like to get themify back if I can. 

Thanks!

**Comment by scmanjarrez** [comment] 2023-03-04 22:46
It's really difficult to debug a problem without a log file... I don't use custom CSS, just the default one (and discoranged theme)

**Comment by AndyShap2020** [comment] 2023-03-04 22:53
[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10889831/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment] 2023-03-04 23:08
Ok, I think I have detected the problem. I'll release a hotfix. Also, take into account that you have PrintFailed checked, that means that every stopped/cancelled print is increasing the counter.

**Comment by AndyShap2020** [comment] 2023-03-04 23:10
A little confusing... I DO have PrintFailed checked. I thought that means DO NOT use failed prints in the count. But you are saying that when checked it means DO count failed prints in the count?

**Comment by AndyShap2020** [comment] 2023-03-04 23:11
P.S. I can't believe how responsive you are! I am still more than happy to continue beta testing with you.

**Comment by scmanjarrez** [comment] 2023-03-04 23:13
From the README: 
> Take into account failed prints in the counter. Default: disabled (only successful prints increase the counter).

Checked -> stopped/cancelled prints increase the counter
Unchecked -> only successful prints increase the counter

It used to have other description in old versions, but I reworded it to be more clear, sorry for the confusion

**Comment by scmanjarrez** [comment] 2023-03-05 10:47
I've released a new version, it should pop up in the following hours in your octoprint instance.

**Comment by scmanjarrez** [comment] 2023-03-13 16:31
hi, have you encountered the same error after last update (ABL still triggering)? Also, I'll try to add custom CSS rules at least for my buttons so it works even with themeify material design.

**Comment by AndyShap2020** [comment] 2023-03-13 18:50
It’s been a bit of a crazy week. I have not yet had a chance to install the new update. I will do it today and run several small jobs and get back to you.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-13 18:52
Same, don't worry, when you have time. Thanks!

**Comment by AndyShap2020** [comment] 2023-03-14 00:33
I’m just getting started on testing.  Octoprint is coming up saying 0.5.0 is ready to install. Is this the latest release I should be testing?

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-14 00:33
Yes, that's the latest version

**Comment by AndyShap2020** [comment] 2023-03-14 00:36
I think you know this: As of 0.5.0 Themify still needs to be disabled to see color and counter of SmartABL.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-14 00:37
Yes, I'm planning to create a custom "theme" for these buttons (instead of using bootstrap btn colors) in order to fix that, but I've been very busy lately, sorry.

**Comment by AndyShap2020** [comment] 2023-03-14 00:38
Don’t apologize, I’m just making sure I understood what you said previously.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment] 2023-03-14 00:47
Should open this request in a new thread?: As of now, SmartABL only heats the bed, then when up to temp, it does an ABL.  I’d like it to heat the head at the same time, so I don’t need to wait after an ABL.  Can I just add this in the custom GCODE?

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-14 00:49
Yes, you can add several gcodes, just separate them with a comma. Btw, SmartABL has nothing to do with hotend/bed, it only cares about bed leveling commands. If the bed/hotend isn't heating, it should be in your start gcode.

This is a start gcode to achieve something like that (cura, but it should be similar with PrusaSlicer/SuperSlicer, just check the variables):
```gcode
; start of custom start-gcode
; start preheating
M140 S{material_bed_temperature_layer_0}; start preheating bed
M104 S{material_print_temperature_layer_0} ; start preheating hotend
G90 ; absolute positioning
M82 ; set extruder in relative mode
G28 ; move X/Y/Z to min endstops
M190 S{material_bed_temperature_layer_0} ; heat to Cura Bed setting
M109 S{material_print_temperature_layer_0} ; heat to Cura Hotend setting
G29 ; autobed leveling
G1 X5 Y0 Z0.2 F2000 ; go to purge area
G92 E0 ; reset extruded lenght
G1 Y100 E15 F500 ; purge first line
G92 E0 ; reset extruded lenght
G1 Z2 ; raise 2mm z axis to prevent scratches
```

**Comment by AndyShap2020** [comment] 2023-03-14 01:05
No, it does heat up the bed before abl, but I'd like it to heat up the hotend as well. I'll add gcode in smartabl.

First print started, did an abl as expected.



_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.******@***.***>
Web: www.asconsulting.com<http://www.asconsulting.com/>

________________________________

**Comment by scmanjarrez** [comment] 2023-03-14 01:07
Yes, but it's a misconfiguration in your slicer. You should use M140 and M104 to start preheating, then M190 and M109 to wait for the temperature reaches the required value.

**Comment by AndyShap2020** [comment] 2023-03-16 19:38
Unfortunately, we aren't quite there yet.  I started a print on Monday and it did an ABL and started a print.  This is now my second print (2 days later, I have it set for 5 prints or 10days).  And it is starting an ABL.  Logs attached.
[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/10995173/plugin_SmartABL.log)

**Comment by AndyShap2020** [comment] 2023-03-16 20:59
I think this caht does belong in this thread:

I already have the codes you mention in my start code:

______________________________________
; Ender 3 Custom Start G-code
M413 S0 ; Disable power-loss recovery
G92 E0 ; Reset Extruder
G28 ; home
;G29 ; Run Auto Bed Level on every print
;M420 S1 Z2 ; Load stored Auto Bed Level

​;------------------------------------------
;*** Start Dual Nozzle/Bed Preheating ***
M140 S{material_bed_temperature_layer_0} ; start preheating the bed
M104 S{material_print_temperature_layer_0} ﻿T0 ; start preheating hotend

M190 S{material_bed_temperature_layer_0} ; heat to Cura Bed setting
M109 S{material_print_temperature_layer_0} ﻿T0 ; heat to Cura Hotend
;*** End Preheating ***
​;------------------------------------------

;*** Signal Print Start Tone
M300 S1000 P500 ; chirp to indicate starting to print
;*** End Single Start Tone

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
_________________________________________________________

What I think may be the issue is that my preheating section is AFTER the G29.  DO you think that is the issue?
_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-16 21:58
Ok. I got a clue from the logs. For some reason, the event PrintStarted from octoprint is delayed. The plugin is receiving the event PrintStarted (the one I use to start the mesh check) after receiving G29, so the check returns "incorrect bed mesh". The normal behaviour is, the plugin receives PrintStarted, then I query the bed mesh with M420 V1, if it returns the mesh, I set a flag. Then when I receive G29 I check that flag, if all went good (the flag exists), ABL is skipped. If the flag is missing, ABL is triggered (your case)

**Comment by scmanjarrez** [comment] 2023-03-18 11:00
Hi, I've pre-released a new version with a (I hope) fix for this error. Can you check it? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1rc1

Edit: I also added the fixes for themeify theme...
Edit2: I recommend this plugin https://github.com/LazeMSS/OctoPrint-UICustomizer, far better than themeify and is active (unlike themeify, whose last update was on 2020...)

**Comment by AndyShap2020** [comment] 2023-03-18 15:35
I should be able to do it today.  Print 2/5 also did an abl.  Where is the software? Is it already on GitHub?



_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.******@***.***>
Web: www.asconsulting.com<http://www.asconsulting.com/>
________________________________

**Comment by scmanjarrez** [comment] 2023-03-18 15:37
Yes, I haven't released it yet to octoprint. But you can find the pre-release here https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1rc1. Also, check this plugin https://github.com/LazeMSS/OctoPrint-UICustomizer, far better than themeify (btw, I've added the fix to your themeify problem)

**Comment by AndyShap2020** [comment] 2023-03-18 22:37
Installed update and starting first print now.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment] 2023-03-18 22:40
I’ve enabled Themify, I can now read RESTRICTED, but it is Grey and not green as when Themify is diabled.  So, Grey versus white is still hard to tell if restricted is on or off.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-19 09:44
Can you share a screenshot?

**Comment by AndyShap2020** [comment] 2023-03-19 15:49
Just starting my 3rd print. No ABL, this is the first time this is working!

![SmartABL 1](https://user-images.githubusercontent.com/71109919/226187384-02ab459e-9310-4537-b7d8-0bd76899af4d.jpg)
![SmartABL 2](https://user-images.githubusercontent.com/71109919/226187385-c6b84948-50d7-4b5d-a1f4-076cda2e9d2d.jpg)
![SmartABL 3](https://user-images.githubusercontent.com/71109919/226187386-460507aa-ec8d-4f90-9d47-7b245645dc34.jpg)

**Comment by scmanjarrez** [comment] 2023-03-19 15:50
Yes! I'm working on the css fix.

**Comment by scmanjarrez** [comment] 2023-03-19 16:06
Can you check this version? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1rc2 It should give some colors to your buttons :)
Also, check [UICustomizer ](https://plugins.octoprint.org/plugins/uicustomizer/)plugin, is the next-generation themeify, way better (and maintained).

**Comment by AndyShap2020** [comment] 2023-03-19 16:37
I am just heading out of town today. I’ll be back tomorrow and have prints to start as soon as I get back. I’ll let you know tomorrow afternoon.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment] 2023-03-21 00:54
Green color is back! Started my fourth print- no ABL!

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment] 2023-03-21 16:51
Well, we may not be out of the woods yet. It did the ABL on the first print (with the previous version).  I upgraded to the newest about print 3.  It completed 5/5 with only an ABL on the first print.  But it is now starting print 1/5 and it did not do an ABL.
[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11031346/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment] 2023-03-21 16:54
Can you share a screenshot from SmartABL settings? Maybe you have custom gcode enabled? Also, can you share your start gcode?

**Comment by AndyShap2020** [comment] 2023-03-21 16:59
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

​;------------------------------------------
;*** Start Dual Nozzle/Bed Preheating ***
;M140 S{material_bed_temperature_layer_0} ; start preheating the bed
;M104 S{material_print_temperature_layer_0} ﻿T0 ; start preheating hotend

G28 ; home
;G29 ; Run Auto Bed Level on every print
M420 S1 Z2; Use Level Mesh up to 2mm;

M190 S{material_bed_temperature_layer_0} ; heat to Cura Bed setting
M109 S{material_print_temperature_layer_0} ﻿T0 ; heat to Cura Hotend

![SmartABL-2](https://user-images.githubusercontent.com/71109919/226685133-4b375ee2-80cb-4c81-8757-24f26a09f8f9.jpg)![SmartABL-1](https://user-images.githubusercontent.com/71109919/226685127-e479338c-f44e-4f7d-bf4e-18dd7f3619bc.jpg) squish

**Comment by scmanjarrez** [comment] 2023-03-21 17:00
Can you test this one? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1rc3
This one should work now (I was doing a full comparison instead of partial comparison. You have M420 S1 Z2 but I was comparing it with M420 only, it should pass the check if M420 is present)

**Comment by AndyShap2020** [comment] 2023-03-21 17:03
My current print should be done in about 5 hours. I’ll uninstall and re-install SmartABL as soon as it is done.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment] 2023-03-21 21:22
I uninstalled Rc2 and installed Rc3.  Just starting my first print and it is doing an ABL!

I’ll keep you informed.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-22 21:27
Hey, I've found a bug with ABL skip. Can you update to rc5?https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1rc5

**Comment by AndyShap2020** [comment] 2023-03-22 23:14
I’m in a 20 hour print.  I’ll get this installed tomorrow.  Should I uninstall the previous version first? Or, can I just install the new version on top of the old?

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment] 2023-03-22 23:14
I think you can install it on top

**Comment by AndyShap2020** [comment] 2023-03-23 16:54
RC5 is installed.  I started print # 3/5 and (properly) it did not do an ABL.

**Comment by AndyShap2020** [comment] 2023-03-25 14:41
Success! Prints 4/5 & 5/5 printed great WITHOUT an ABL. I just started 1/5 and it is doing an ABL!

**Comment by scmanjarrez** [comment] 2023-03-25 14:43
yes! I think I'll release 0.5.1 then. Thank you!

**Comment by scmanjarrez** [comment] 2023-03-25 15:00
Fixed on https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1

**Closed as completed by scmanjarrez** 2023-03-25 15:00 UTC
Labels: bug, included-in-next-release

**Comment by AndyShap2020** [comment] 2023-03-30 14:44
I’ve gone a couple of rounds of 5 prints. All is working well!

**Comment by scmanjarrez** [comment] 2023-03-30 14:45
Nice! Thanks for your feedback. Appreciated :)
